name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress Theme Deploy
        uses: Codeinwp/action-wordpress-theme-deploy@primary
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: untroubled